# 用户无需手动改此文件，所有字段由 WebUI 写入
bot_token: ""
admin_ids: []
user_ids: []
group_ids: []
channel_ids: []
enable_search: true
enable_down: true
enable_sub: true
enable_refresh: true
enable_disk: true
enable_site: true
enable_sys: true
show_keyboard: true
